### ISSUE TITLE
Support for dbt-core 1.3.0

### ISSUE THREAD

**Issue by NoamMosko** [fal-ai/fal#590]
**Context**
currently fal doesn't work with dbt-core 1.3.0

**Additional context**
ImportError: cannot import name 'DEFAULT_PROFILES_DIR' from 'dbt.config.profile' (/opt/dbt_venv/lib/python3.7/site-packages/dbt/config/profile.py)

this is the error i receive

**Comment by chamini2** [comment]
This issue should go away with the latest version released, [0.7.0](https://pypi.org/project/fal/0.7.0/).

Please let us know if anything else breaks!

Also, check out necessary [changes for fal Python models](https://blog.fal.ai/python-data-modes/) to work with 1.3.0.
